# Generated by Django 3.0.4 on 2024-06-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalStress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anxiety_level', models.IntegerField()),
                ('self_esteem', models.IntegerField()),
                ('mental_health_history', models.IntegerField()),
                ('depression', models.IntegerField()),
                ('headache', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('sleep_quality', models.IntegerField()),
                ('breathing_problem', models.IntegerField()),
                ('noise_level', models.IntegerField()),
                ('living_conditions', models.IntegerField()),
                ('safety', models.IntegerField()),
                ('basic_needs', models.IntegerField()),
                ('academic_performance', models.IntegerField()),
                ('study_load', models.IntegerField()),
                ('teacher_student_relationship', models.IntegerField()),
                ('future_career_concerns', models.IntegerField()),
                ('social_support', models.IntegerField()),
                ('peer_pressure', models.IntegerField()),
                ('extracurricular_activities', models.IntegerField()),
                ('bullying', models.IntegerField()),
                ('stress_level', models.IntegerField()),
            ],
        ),
    ]
